In [2]:
import torch

x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[[1, 2], [3, 4]],[[1, 2], [3, 4]], [[1, 2], [3, 4]]])
# print(x)
# print(x.type())

# print(x.size())
# print(x.shape)
# print(x.ndimension())

print(y.shape)
# print(y.ndimension())
print(len(y.shape))

torch.Size([3, 2, 2])
3
3


In [7]:
x = torch.FloatTensor([[[1, 2], [3, 4]],[[1, 2], [3, 4]], [[1, 2], [3, 4]]])

print(x.shape)
print(x)

x0 = x.unsqueeze(0) #[3,2,2] -> [1,3,2,2]
x1 = x.unsqueeze(1) #[3,2,2] -> [3,1,2,2]
x2 = x.unsqueeze(2) #[3,2,2] -> [3,2,1,2]
x3 = x.unsqueeze(3) #[3,2,2] -> [3,2,2,1]
print(x0)
print(x1)
print(x2)
print(x3)

torch.Size([3, 2, 2])
tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])
tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]]])
tensor([[[[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]]]])
tensor([[[[1., 2.]],

         [[3., 4.]]],


        [[[1., 2.]],

         [[3., 4.]]],


        [[[1., 2.]],

         [[3., 4.]]]])
tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]]],


        [[[1.],
          [2.]],

         [[3.],
          [4.]]],


        [[[1.],
          [2.]],

         [[3.],
          [4.]]]])


In [15]:
# x3.shape
# print(x3.squeeze().shape)
# print(x2.squeeze().shape)
# print(x1.squeeze().shape)
# print(x0.squeeze().shape)
x.shape

xt = x.unsqueeze(0).unsqueeze(1).unsqueeze(0).unsqueeze(5) #[3,2,2] -> [1,1,1,3,2,1,2]
print(xt.squeeze().shape)

torch.Size([3, 2, 2])


In [22]:
x.view(3,1,-1)

tensor([[[1., 2., 3., 4.]],

        [[1., 2., 3., 4.]],

        [[1., 2., 3., 4.]]])

In [24]:
x = torch.FloatTensor([[1,2], [3,4], [5,6]])
w = torch.randn(1, 2, dtype=torch.float)
b = torch.randn(3, 1, dtype=torch.float)

print(x @ w.T + b)
# torch.mm(x, w.T)
# torch.t(w) == w.T

# print(x)
# print(w)
# print(b)

tensor([[-0.4924],
        [ 1.3870],
        [ 4.3300]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 0.9860, -0.3191]])
tensor([[-0.8402],
        [-0.2946],
        [ 1.3147]])


In [27]:
w = torch.tensor(4.0, requires_grad=True)
a = w*3
l = a**2
l.backward()
print(w.grad)

tensor(72.)


In [29]:
x_train = torch.FloatTensor([[1,2],[3,2],[3,7],[1,1],[1,0]])
y_train = torch.FloatTensor([[4],[8],[23],[1],[-2]])

w = torch.randn(2,1)
b = torch.randn(1)

lr = 0.01

In [35]:

for epoch in range(3001):
  w.requires_grad_(True)
  b.requires_grad_(True)

  h = x_train @ w + b
  cost = ((h - y_train) ** 2).mean()

  cost.backward()

  with torch.no_grad():
    w = w - lr * w.grad
    b = b - lr * b.grad

    if epoch % 100 == 0:
      print(epoch, cost.item(), w.squeeze(), b)

0 203.93374633789062 tensor([ 0.3771, -0.2369]) tensor([1.7862])
100 2.7184784412384033 tensor([0.2382, 3.1729]) tensor([-0.4929])
200 1.3163727521896362 tensor([0.5758, 3.2412]) tensor([-1.5972])
300 0.6754717230796814 tensor([0.9608, 3.1862]) tensor([-2.2901])
400 0.34712421894073486 tensor([1.2529, 3.1350]) tensor([-2.7756])
500 0.1783936470746994 tensor([1.4642, 3.0970]) tensor([-3.1224])
600 0.09167958796024323 tensor([1.6159, 3.0695]) tensor([-3.3709])
700 0.0471157506108284 tensor([1.7246, 3.0498]) tensor([-3.5490])
800 0.02421371079981327 tensor([1.8026, 3.0357]) tensor([-3.6767])
900 0.012443939223885536 tensor([1.8585, 3.0256]) tensor([-3.7682])
1000 0.006395167205482721 tensor([1.8985, 3.0184]) tensor([-3.8338])
1100 0.0032866070978343487 tensor([1.9273, 3.0132]) tensor([-3.8809])
1200 0.0016890279948711395 tensor([1.9479, 3.0094]) tensor([-3.9146])
1300 0.0008680351311340928 tensor([1.9626, 3.0068]) tensor([-3.9388])
1400 0.00044609460746869445 tensor([1.9732, 3.0048]) tens

In [37]:
x_test = torch.FloatTensor([[5,10],[2,7],[10,3]])

y_test = x_test @ w + b

print(y_test)

tensor([[35.9998],
        [21.0001],
        [24.9990]])


In [38]:
from sklearn.linear_model import LinearRegression

x = [[1,2],[3,2],[3,7],[1,1],[1,0]]
y = [[4],[8],[23],[1],[-2]]

lr = LinearRegression()
lr.fit(x, y)

print(lr.coef_, lr.intercept_)

x_test = [[5,10],[2,7],[10,3]]

y_test = lr.predict(x_test)
print(y_test)

[[2. 3.]] [-4.]
[[36.]
 [21.]
 [25.]]
