In [6]:
import torch

x_train = torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = torch.FloatTensor([[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]])

W = torch.randn(4,3,requires_grad=True)
b = torch.randn(1,3,requires_grad=True)

optim = torch.optim.Adam([W,b],lr=0.1)

for epoch in range(3001):

  h = torch.softmax(torch.mm(x_train, W)+b, dim=1)
  # h = (torch.mm(x_train, W)+b).softmax(dim=1)
  cost = -torch.mean(torch.sum(y_train * torch.log(h), dim=1))
  # cost = -(y_train*torch.log(h)).sum(dim=1).mean()

  # h = torch.mm(x_train, W)+b
  # cost = -torch.mean(torch.sum(y_train * torch.log(torch.softmax(h,dim=1)), dim=1))

  optim.zero_grad()
  cost.backward()
  optim.step()

  with torch.no_grad():
    if epoch % 100 == 0:
      print(epoch, cost.item())


tensor([[-0.4909,  0.4914, -0.6061],
        [ 1.3866, -0.4013,  1.3471],
        [-0.6585,  0.7748,  0.6029],
        [-1.5096, -1.0390, -0.6979]], requires_grad=True)
tensor([[-0.2425, -0.7292, -0.6995]], requires_grad=True)
0 5.412178039550781
100 0.3581276535987854
200 0.23492926359176636
300 0.16263993084430695
400 0.11901606619358063
500 0.09087298810482025
600 0.07163464277982712
700 0.05788714438676834
800 0.04771832376718521
900 0.03998439759016037
1000 0.03396528214216232
1100 0.029188405722379684
1200 0.025333194062113762
1300 0.022176366299390793
1400 0.01955818384885788
1500 0.017362207174301147
1600 0.015501974150538445
1700 0.013912028633058071
1800 0.012542258948087692
1900 0.011353641748428345
2000 0.010315579362213612
2100 0.009403535164892673
2200 0.008598034270107746
2300 0.007883092388510704
2400 0.007245650514960289
2500 0.006674974225461483
2600 0.006162156350910664
2700 0.005699690897017717
2800 0.005281282588839531
2900 0.004901614971458912
3000 0.0045560882426

In [9]:
x_test = torch.tensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]], dtype=torch.float)

h_test = torch.softmax(torch.mm(x_test,W)+b,dim=1)
print(h_test)
print(torch.argmax(h_test, dim=1))

tensor([[1.0000e+00, 1.7427e-17, 1.0706e-34],
        [1.8421e-03, 6.7243e-01, 3.2572e-01],
        [6.7848e-31, 1.1033e-10, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)
tensor([0, 1, 2])


In [11]:
import torch
import torch.nn.functional as F
import torch.nn as nn

x_train = torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

# W = torch.randn(4,3,requires_grad=True)
# b = torch.randn(1,3,requires_grad=True)
# optim = torch.optim.Adam([W,b],lr=0.1)

model = nn.Linear(4,3)
optim = torch.optim.Adam(model.parameters(), lr=0.1)

for epoch in range(3001):

  # h = torch.mm(x_train, W)+b
  h = model(x_train)
  cost = F.cross_entropy(h, y_train)

  optim.zero_grad()
  cost.backward()
  optim.step()

  with torch.no_grad():
    if epoch % 100 == 0:
      print(epoch, cost.item())


0 1.257699966430664
100 0.28990671038627625
200 0.16692619025707245
300 0.1083718091249466
400 0.07638566941022873
500 0.05684909597039223
600 0.043996281921863556
700 0.03507738560438156
800 0.028629301115870476
900 0.02381208911538124
1000 0.020114833489060402
1100 0.01721263863146305
1200 0.01489066518843174
1300 0.013002232648432255
1400 0.011444682255387306
1500 0.010144088417291641
1600 0.009046223014593124
1700 0.008110626600682735
1800 0.007306527346372604
1900 0.006610112264752388
2000 0.006002909503877163
2100 0.005470147356390953
2200 0.0050001246854662895
2300 0.004583302419632673
2400 0.0042119198478758335
2500 0.0038797049783170223
2600 0.0035812901332974434
2700 0.0033122936729341745
2800 0.003069015685468912
2900 0.002848322270438075
3000 0.002647530287504196


In [14]:
import numpy as np
from sklearn.linear_model import LogisticRegression

x_train = np.array([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = np.array([2,2,2,1,1,1,0,0])

model = LogisticRegression(penalty=None)

model.fit(x_train, y_train)

x_test = np.array([[1,11,10,9],[1,3,4,3],[1,1,0,1]])

print(model.predict(x_test))

[0 1 2]
